### PR TITLE
Fix operations with fromCents

### LINKED ISSUE #260: `fromCents` does not play nicely with `multiply`
Love the new ✨ 2.0 release. Unfortunately I'm running into an issue using it in conjunction with `multiply`, for example:

`currency(300, {fromCents: true}).multiply(2).intValue`

I would expect `600` as the output here, but it is actually `6`. 

I can confirm the `intValue` of `currency(300, {fromCents: true}).intValue` is 300 as expected, so it seems like the precision is getting lost along the way of multiplication.

Weirdly, this does not reproduce with `currency(300, {fromCents: true}).divide(2).intValue`, so it seems specific to `multiply` to me.

CC @ryanwood

### PR DESCRIPTION
**Pull request by ryanwood**
I'm actually on an anniversary weekend getaway with my wife but saw #260 and felt bad about the oversight. I still haven't had a chance to use 2.0 yet but wanted to take a crack at fixing the problems based on the assertions by @scurker in https://github.com/scurker/currency.js/issues/260#issuecomment-659675669.

This should fix those particular issues. I also don't use any of the operations (add, subtract, multiply, divide, distribute) of this library which is probably why they were overlooked.

Let me know what you think and feel free to edit this commit if needed or if there are any problems. Hope this helps.

### CODE REVIEW

**Comment by ryanwood** [comment]
@chrisvariety So looking at the code base the existing signature is to just pass a number as an argument. I agree that it would be nice to be able pass a currency instance as an argument. I'm wondering if that should be part of this fix as a new requirement from using fromCents or if it should be considered a separate feature? 

It seems to me that it isn't a contract that's broken like the current operations but a useful enhancement.

@scurker Do you think this needs to be included in the patch or can it be a separate enhancement?

**Comment by scurker** [comment]
`.add()` should take a string, number, or another currency object and I would consider that breaking functionality otherwise.

Sorry to disrupt your weekend getaway! There's no rush on this since the upgrade path to `v2.0.0` is one that most users probably won't have opted into yet, but I hope to take a stab at things this weekend.

**Comment by chrisvariety** [comment]
@scurker You were featured in JavaScript Weekly this week for 2.0, congrats on that 😅

wish I had more time to help other than testing.

image

**Comment by scurker** [comment]
> I'm actually on an anniversary weekend getaway with my wife but saw #260 and felt bad about the oversight.

Don't worry about it! I missed it too, and fortunately it's not a regression since it was a _new_ feature.

**Comment by scurker** [comment]
Fixed with #262

**Pull request closed without merging**
